name: cfp2
recipe: wordpress
config:
  env: dev
  xdebug: true
  php: '7.2'
  via: nginx
  webroot: wordpress
proxy:
  mailhog:
  - mail.cfp2.lndo.site
  pma:
  - pma.cfp2.lndo.site
services:
  appserver:
    composer:
      phpunit/phpunit: '*'
    build:
    - "cd $LANDO_MOUNT && composer update --prefer-source"
    - "bash ./scripts/wp/post-build.sh"
    - "bash ./scripts/wp/install-wp-tests.sh wordpress wordpress wordpress database"
    post-start:
    - "cd $LANDO_MOUNT && composer update --prefer-source"
    - "bash ./scripts/wp/post-start.sh"
    volumes:
    - ./plugins:/app/wp-content/plugins
    - ./wp-content:/app/wp-content
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
    portforward: true
  pma:
    type: phpmyadmin
    hosts:
    - database
    - database.cfp2.internal
  wptest:
    type: php:custom
    overrides:
      services:
        image: chriszarate/wordpress-phpunit
    volumes:
    - .:/app
    - testsuite:/tmp
  laravel:
    type: laravel
    config:
      via: nginx
      database: mariadb
      xdebug: true
      cache: redis
tooling:
  app:
    description: "Start app front-end"
    cmd: "cd $LANDO_MOUNT && cd packages/caldera-forms-pro && yarn start"
    service: node
  composer:
    service: appserver
  wp:
    service: appserver
  wptests:
    service: wptest
    description: Runs WordPress tests
    cmd: "phpunit"
    user:  root
  wptests-now:
    service: wptest
    description: Runs WordPress tests
    cmd: "phpunit --group=now"
    user:  root
  wptests-i:
    service: wptest
    description: Installs WordPress tests
    cmd: "cd $LANDO_MOUNT && bash scripts/wp/install-wp-tests.sh wordpress wordpress wordpress database"
    user:  root
  dbTests:
    service: wptest
    description: Runs cfp2wp/cfp2-db tests using main container
    cmd: "cd $LANDO_MOUNT/php-packages/cfp2-db && composer test:acceptance"
    user:  root
