import React from 'react';

const titleStyle = {
    "alignContent": "normal",
    "alignItems": "normal",
    "alignSelf": "auto",
    "alignmentBaseline": "auto",
    "all": "",
    "animation": "none 0s ease 0s 1 normal none running",
    "animationDelay": "0s",
    "animationDirection": "normal",
    "animationDuration": "0s",
    "animationFillMode": "none",
    "animationIterationCount": "1",
    "animationName": "none",
    "animationPlayState": "running",
    "animationTimingFunction": "ease",
    "backfaceVisibility": "visible",
    "background": "rgba(0, 0, 0, 0) none repeat scroll 0% 0% / auto padding-box border-box",
    "backgroundAttachment": "scroll",
    "backgroundBlendMode": "normal",
    "backgroundClip": "border-box",
    "backgroundColor": "rgba(0, 0, 0, 0)",
    "backgroundImage": "none",
    "backgroundOrigin": "padding-box",
    "backgroundPosition": "0% 0%",
    "backgroundPositionX": "0%",
    "backgroundPositionY": "0%",
    "backgroundRepeat": "repeat",
    "backgroundRepeatX": "",
    "backgroundRepeatY": "",
    "backgroundSize": "auto",
    "baselineShift": "0px",
    "blockSize": "103px",
    "border": "",
    "borderBlockEnd": "1px solid rgba(0, 0, 0, 0)",
    "borderBlockEndColor": "rgba(0, 0, 0, 0)",
    "borderBlockEndStyle": "solid",
    "borderBlockEndWidth": "1px",
    "borderBlockStart": "1px solid rgba(0, 0, 0, 0)",
    "borderBlockStartColor": "rgba(0, 0, 0, 0)",
    "borderBlockStartStyle": "solid",
    "borderBlockStartWidth": "1px",
    "borderBottom": "1px solid rgba(0, 0, 0, 0)",
    "borderBottomColor": "rgba(0, 0, 0, 0)",
    "borderBottomLeftRadius": "0px",
    "borderBottomRightRadius": "0px",
    "borderBottomStyle": "solid",
    "borderBottomWidth": "1px",
    "borderCollapse": "separate",
    "borderColor": "rgba(0, 0, 0, 0)",
    "borderImage": "none",
    "borderImageOutset": "0px",
    "borderImageRepeat": "stretch",
    "borderImageSlice": "100%",
    "borderImageSource": "none",
    "borderImageWidth": "1",
    "borderInlineEnd": "1px solid rgba(0, 0, 0, 0)",
    "borderInlineEndColor": "rgba(0, 0, 0, 0)",
    "borderInlineEndStyle": "solid",
    "borderInlineEndWidth": "1px",
    "borderInlineStart": "0px solid rgba(0, 0, 0, 0)",
    "borderInlineStartColor": "rgba(0, 0, 0, 0)",
    "borderInlineStartStyle": "solid",
    "borderInlineStartWidth": "0px",
    "borderLeft": "0px solid rgba(0, 0, 0, 0)",
    "borderLeftColor": "rgba(0, 0, 0, 0)",
    "borderLeftStyle": "solid",
    "borderLeftWidth": "0px",
    "borderRadius": "0px",
    "borderRight": "1px solid rgba(0, 0, 0, 0)",
    "borderRightColor": "rgba(0, 0, 0, 0)",
    "borderRightStyle": "solid",
    "borderRightWidth": "1px",
    "borderSpacing": "0px 0px",
    "borderStyle": "solid",
    "borderTop": "1px solid rgba(0, 0, 0, 0)",
    "borderTopColor": "rgba(0, 0, 0, 0)",
    "borderTopLeftRadius": "0px",
    "borderTopRightRadius": "0px",
    "borderTopStyle": "solid",
    "borderTopWidth": "1px",
    "borderWidth": "1px 1px 1px 0px",
    "bottom": "auto",
    "boxShadow": "none",
    "boxSizing": "border-box",
    "breakAfter": "auto",
    "breakBefore": "auto",
    "breakInside": "auto",
    "bufferedRendering": "auto",
    "captionSide": "top",
    "caretColor": "rgb(25, 30, 35)",
    "clear": "none",
    "clip": "auto",
    "clipPath": "none",
    "clipRule": "nonzero",
    "color": "rgb(25, 30, 35)",
    "colorInterpolation": "srgb",
    "colorInterpolationFilters": "linearrgb",
    "colorRendering": "auto",
    "columnCount": "auto",
    "columnFill": "balance",
    "columnGap": "normal",
    "columnRule": "0px none rgb(25, 30, 35)",
    "columnRuleColor": "rgb(25, 30, 35)",
    "columnRuleStyle": "none",
    "columnRuleWidth": "0px",
    "columnSpan": "none",
    "columnWidth": "auto",
    "columns": "auto auto",
    "contain": "none",
    "content": "normal",
    "counterIncrement": "none",
    "counterReset": "none",
    "cursor": "text",
    "cx": "0px",
    "cy": "0px",
    "d": "none",
    "direction": "ltr",
    "display": "block",
    "dominantBaseline": "auto",
    "emptyCells": "show",
    "fill": "rgb(0, 0, 0)",
    "fillOpacity": "1",
    "fillRule": "nonzero",
    "filter": "none",
    "flex": "0 1 auto",
    "flexBasis": "auto",
    "flexDirection": "column",
    "flexFlow": "column nowrap",
    "flexGrow": "0",
    "flexShrink": "1",
    "flexWrap": "nowrap",
    "float": "none",
    "floodColor": "rgb(0, 0, 0)",
    "floodOpacity": "1",
    "font": "normal normal 700 normal 45px / 63px -apple-system, system-ui, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", sans-serif",
    "fontDisplay": "",
    "fontFamily": "-apple-system, system-ui, \"Segoe UI\", Roboto, Oxygen, Ubuntu, Cantarell, \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", sans-serif",
    "fontFeatureSettings": "normal",
    "fontKerning": "auto",
    "fontSize": "45px",
    "fontStretch": "100%",
    "fontStyle": "normal",
    "fontVariant": "normal",
    "fontVariantCaps": "normal",
    "fontVariantEastAsian": "normal",
    "fontVariantLigatures": "normal",
    "fontVariantNumeric": "normal",
    "fontVariationSettings": "normal",
    "fontWeight": "700",
    "gap": "normal normal",
    "grid": "none / none / none / row / auto / auto",
    "gridArea": "auto / auto / auto / auto",
    "gridAutoColumns": "auto",
    "gridAutoFlow": "row",
    "gridAutoRows": "auto",
    "gridColumn": "auto / auto",
    "gridColumnEnd": "auto",
    "gridColumnGap": "normal",
    "gridColumnStart": "auto",
    "gridGap": "normal normal",
    "gridRow": "auto / auto",
    "gridRowEnd": "auto",
    "gridRowGap": "normal",
    "gridRowStart": "auto",
    "gridTemplate": "none / none / none",
    "gridTemplateAreas": "none",
    "gridTemplateColumns": "none",
    "gridTemplateRows": "none",
    "height": "103px",
    "hyphens": "manual",
    "imageRendering": "auto",
    "inlineSize": "775.5px",
    "isolation": "auto",
    "justifyContent": "normal",
    "justifyItems": "normal",
    "justifySelf": "auto",
    "left": "auto",
    "letterSpacing": "normal",
    "lightingColor": "rgb(255, 255, 255)",
    "lineBreak": "auto",
    "lineHeight": "63px",
    "listStyle": "disc outside none",
    "listStyleImage": "none",
    "listStylePosition": "outside",
    "listStyleType": "disc",
    "margin": "0px",
    "marginBlockEnd": "0px",
    "marginBlockStart": "0px",
    "marginBottom": "0px",
    "marginInlineEnd": "0px",
    "marginInlineStart": "0px",
    "marginLeft": "0px",
    "marginRight": "0px",
    "marginTop": "0px",
    "marker": "",
    "markerEnd": "none",
    "markerMid": "none",
    "markerStart": "none",
    "mask": "none",
    "maskType": "luminance",
    "maxBlockSize": "none",
    "maxHeight": "none",
    "maxInlineSize": "none",
    "maxWidth": "none",
    "maxZoom": "",
    "minBlockSize": "0px",
    "minHeight": "0px",
    "minInlineSize": "0px",
    "minWidth": "0px",
    "minZoom": "",
    "mixBlendMode": "normal",
    "objectFit": "fill",
    "objectPosition": "50% 50%",
    "offset": "none 0px auto 0deg",
    "offsetDistance": "0px",
    "offsetPath": "none",
    "offsetRotate": "auto 0deg",
    "opacity": "1",
    "order": "0",
    "orientation": "",
    "orphans": "2",
    "outline": "rgba(0, 0, 0, 0) solid 1px",
    "outlineColor": "rgba(0, 0, 0, 0)",
    "outlineOffset": "0px",
    "outlineStyle": "solid",
    "outlineWidth": "1px",
    "overflow": "hidden",
    "overflowAnchor": "auto",
    "overflowWrap": "break-word",
    "overflowX": "hidden",
    "overflowY": "hidden",
    "overscrollBehavior": "auto auto",
    "overscrollBehaviorX": "auto",
    "overscrollBehaviorY": "auto",
    "padding": "19px 14px",
    "paddingBlockEnd": "19px",
    "paddingBlockStart": "19px",
    "paddingBottom": "19px",
    "paddingInlineEnd": "14px",
    "paddingInlineStart": "14px",
    "paddingLeft": "14px",
    "paddingRight": "14px",
    "paddingTop": "19px",
    "page": "",
    "pageBreakAfter": "auto",
    "pageBreakBefore": "auto",
    "pageBreakInside": "auto",
    "paintOrder": "normal",
    "perspective": "none",
    "perspectiveOrigin": "387.75px 51.5px",
    "placeContent": "normal normal",
    "placeItems": "normal normal",
    "placeSelf": "auto auto",
    "pointerEvents": "auto",
    "position": "static",
    "quotes": "",
    "r": "0px",
    "resize": "none",
    "right": "auto",
    "rowGap": "normal",
    "rx": "auto",
    "ry": "auto",
    "scrollBehavior": "auto",
    "scrollMargin": "0px",
    "scrollMarginBlock": "0px",
    "scrollMarginBlockEnd": "0px",
    "scrollMarginBlockStart": "0px",
    "scrollMarginBottom": "0px",
    "scrollMarginInline": "0px",
    "scrollMarginInlineEnd": "0px",
    "scrollMarginInlineStart": "0px",
    "scrollMarginLeft": "0px",
    "scrollMarginRight": "0px",
    "scrollMarginTop": "0px",
    "scrollPadding": "auto",
    "scrollPaddingBlock": "auto",
    "scrollPaddingBlockEnd": "auto",
    "scrollPaddingBlockStart": "auto",
    "scrollPaddingBottom": "auto",
    "scrollPaddingInline": "auto",
    "scrollPaddingInlineEnd": "auto",
    "scrollPaddingInlineStart": "auto",
    "scrollPaddingLeft": "auto",
    "scrollPaddingRight": "auto",
    "scrollPaddingTop": "auto",
    "scrollSnapAlign": "none",
    "scrollSnapStop": "normal",
    "scrollSnapType": "none",
    "shapeImageThreshold": "0",
    "shapeMargin": "0px",
    "shapeOutside": "none",
    "shapeRendering": "auto",
    "size": "",
    "speak": "normal",
    "src": "",
    "stopColor": "rgb(0, 0, 0)",
    "stopOpacity": "1",
    "stroke": "none",
    "strokeDasharray": "none",
    "strokeDashoffset": "0px",
    "strokeLinecap": "butt",
    "strokeLinejoin": "miter",
    "strokeMiterlimit": "4",
    "strokeOpacity": "1",
    "strokeWidth": "1px",
    "tabSize": "8",
    "tableLayout": "auto",
    "textAlign": "start",
    "textAlignLast": "auto",
    "textAnchor": "start",
    "textCombineUpright": "none",
    "textDecoration": "none solid rgb(25, 30, 35)",
    "textDecorationColor": "rgb(25, 30, 35)",
    "textDecorationLine": "none",
    "textDecorationSkipInk": "auto",
    "textDecorationStyle": "solid",
    "textIndent": "0px",
    "textOrientation": "mixed",
    "textOverflow": "clip",
    "textRendering": "auto",
    "textShadow": "none",
    "textSizeAdjust": "auto",
    "textTransform": "none",
    "textUnderlinePosition": "auto",
    "top": "auto",
    "touchAction": "auto",
    "transform": "none",
    "transformBox": "view-box",
    "transformOrigin": "387.75px 51.5px",
    "transformStyle": "flat",
    "transition": "border 0.1s ease-out 0s, box-shadow 0.1s linear 0s",
    "transitionDelay": "0s, 0s",
    "transitionDuration": "0.1s, 0.1s",
    "transitionProperty": "border, box-shadow",
    "transitionTimingFunction": "ease-out, linear",
    "unicodeBidi": "normal",
    "unicodeRange": "",
    "userSelect": "auto",
    "userZoom": "",
    "vectorEffect": "none",
    "verticalAlign": "baseline",
    "visibility": "visible",
    "webkitAlignContent": "normal",
    "webkitAlignItems": "normal",
    "webkitAlignSelf": "auto",
    "webkitAnimation": "none 0s ease 0s 1 normal none running",
    "webkitAnimationDelay": "0s",
    "webkitAnimationDirection": "normal",
    "webkitAnimationDuration": "0s",
    "webkitAnimationFillMode": "none",
    "webkitAnimationIterationCount": "1",
    "webkitAnimationName": "none",
    "webkitAnimationPlayState": "running",
    "webkitAnimationTimingFunction": "ease",
    "webkitAppRegion": "none",
    "webkitAppearance": "none",
    "webkitBackfaceVisibility": "visible",
    "webkitBackgroundClip": "border-box",
    "webkitBackgroundOrigin": "padding-box",
    "webkitBackgroundSize": "auto",
    "webkitBorderAfter": "1px solid rgba(0, 0, 0, 0)",
    "webkitBorderAfterColor": "rgba(0, 0, 0, 0)",
    "webkitBorderAfterStyle": "solid",
    "webkitBorderAfterWidth": "1px",
    "webkitBorderBefore": "1px solid rgba(0, 0, 0, 0)",
    "webkitBorderBeforeColor": "rgba(0, 0, 0, 0)",
    "webkitBorderBeforeStyle": "solid",
    "webkitBorderBeforeWidth": "1px",
    "webkitBorderBottomLeftRadius": "0px",
    "webkitBorderBottomRightRadius": "0px",
    "webkitBorderEnd": "1px solid rgba(0, 0, 0, 0)",
    "webkitBorderEndColor": "rgba(0, 0, 0, 0)",
    "webkitBorderEndStyle": "solid",
    "webkitBorderEndWidth": "1px",
    "webkitBorderHorizontalSpacing": "0px",
    "webkitBorderImage": "none",
    "webkitBorderRadius": "0px",
    "webkitBorderStart": "0px solid rgba(0, 0, 0, 0)",
    "webkitBorderStartColor": "rgba(0, 0, 0, 0)",
    "webkitBorderStartStyle": "solid",
    "webkitBorderStartWidth": "0px",
    "webkitBorderTopLeftRadius": "0px",
    "webkitBorderTopRightRadius": "0px",
    "webkitBorderVerticalSpacing": "0px",
    "webkitBoxAlign": "stretch",
    "webkitBoxDecorationBreak": "slice",
    "webkitBoxDirection": "normal",
    "webkitBoxFlex": "0",
    "webkitBoxOrdinalGroup": "1",
    "webkitBoxOrient": "horizontal",
    "webkitBoxPack": "start",
    "webkitBoxReflect": "none",
    "webkitBoxShadow": "none",
    "webkitBoxSizing": "border-box",
    "webkitClipPath": "none",
    "webkitColumnBreakAfter": "auto",
    "webkitColumnBreakBefore": "auto",
    "webkitColumnBreakInside": "auto",
    "webkitColumnCount": "auto",
    "webkitColumnGap": "normal",
    "webkitColumnRule": "0px none rgb(25, 30, 35)",
    "webkitColumnRuleColor": "rgb(25, 30, 35)",
    "webkitColumnRuleStyle": "none",
    "webkitColumnRuleWidth": "0px",
    "webkitColumnSpan": "none",
    "webkitColumnWidth": "auto",
    "webkitColumns": "auto auto",
    "webkitFilter": "none",
    "webkitFlex": "0 1 auto",
    "webkitFlexBasis": "auto",
    "webkitFlexDirection": "column",
    "webkitFlexFlow": "column nowrap",
    "webkitFlexGrow": "0",
    "webkitFlexShrink": "1",
    "webkitFlexWrap": "nowrap",
    "webkitFontFeatureSettings": "normal",
    "webkitFontSizeDelta": "",
    "webkitFontSmoothing": "subpixel-antialiased",
    "webkitHighlight": "none",
    "webkitHyphenateCharacter": "auto",
    "webkitJustifyContent": "normal",
    "webkitLineBreak": "auto",
    "webkitLineClamp": "none",
    "webkitLocale": "\"en-US\"",
    "webkitLogicalHeight": "103px",
    "webkitLogicalWidth": "775.5px",
    "webkitMarginAfter": "0px",
    "webkitMarginAfterCollapse": "collapse",
    "webkitMarginBefore": "0px",
    "webkitMarginBeforeCollapse": "collapse",
    "webkitMarginBottomCollapse": "collapse",
    "webkitMarginCollapse": "",
    "webkitMarginEnd": "0px",
    "webkitMarginStart": "0px",
    "webkitMarginTopCollapse": "collapse",
    "webkitMask": "",
    "webkitMaskBoxImage": "none",
    "webkitMaskBoxImageOutset": "0px",
    "webkitMaskBoxImageRepeat": "stretch",
    "webkitMaskBoxImageSlice": "0 fill",
    "webkitMaskBoxImageSource": "none",
    "webkitMaskBoxImageWidth": "auto",
    "webkitMaskClip": "border-box",
    "webkitMaskComposite": "source-over",
    "webkitMaskImage": "none",
    "webkitMaskOrigin": "border-box",
    "webkitMaskPosition": "0% 0%",
    "webkitMaskPositionX": "0%",
    "webkitMaskPositionY": "0%",
    "webkitMaskRepeat": "repeat",
    "webkitMaskRepeatX": "",
    "webkitMaskRepeatY": "",
    "webkitMaskSize": "auto",
    "webkitMaxLogicalHeight": "none",
    "webkitMaxLogicalWidth": "none",
    "webkitMinLogicalHeight": "0px",
    "webkitMinLogicalWidth": "0px",
    "webkitOpacity": "1",
    "webkitOrder": "0",
    "webkitPaddingAfter": "19px",
    "webkitPaddingBefore": "19px",
    "webkitPaddingEnd": "14px",
    "webkitPaddingStart": "14px",
    "webkitPerspective": "none",
    "webkitPerspectiveOrigin": "387.75px 51.5px",
    "webkitPerspectiveOriginX": "",
    "webkitPerspectiveOriginY": "",
    "webkitPrintColorAdjust": "economy",
    "webkitRtlOrdering": "logical",
    "webkitRubyPosition": "before",
    "webkitShapeImageThreshold": "0",
    "webkitShapeMargin": "0px",
    "webkitShapeOutside": "none",
    "webkitTapHighlightColor": "rgba(0, 0, 0, 0.4)",
    "webkitTextCombine": "none",
    "webkitTextDecorationsInEffect": "none",
    "webkitTextEmphasis": "",
    "webkitTextEmphasisColor": "rgb(25, 30, 35)",
    "webkitTextEmphasisPosition": "over right",
    "webkitTextEmphasisStyle": "none",
    "webkitTextFillColor": "rgb(25, 30, 35)",
    "webkitTextOrientation": "vertical-right",
    "webkitTextSecurity": "none",
    "webkitTextSizeAdjust": "auto",
    "webkitTextStroke": "",
    "webkitTextStrokeColor": "rgb(25, 30, 35)",
    "webkitTextStrokeWidth": "0px",
    "webkitTransform": "none",
    "webkitTransformOrigin": "387.75px 51.5px",
    "webkitTransformOriginX": "",
    "webkitTransformOriginY": "",
    "webkitTransformOriginZ": "",
    "webkitTransformStyle": "flat",
    "webkitTransition": "border 0.1s ease-out 0s, box-shadow 0.1s linear 0s",
    "webkitTransitionDelay": "0s, 0s",
    "webkitTransitionDuration": "0.1s, 0.1s",
    "webkitTransitionProperty": "border, box-shadow",
    "webkitTransitionTimingFunction": "ease-out, linear",
    "webkitUserDrag": "auto",
    "webkitUserModify": "read-only",
    "webkitUserSelect": "auto",
    "webkitWritingMode": "horizontal-tb",
    "whiteSpace": "pre-wrap",
    "widows": "2",
    "width": "775.5px",
    "willChange": "auto",
    "wordBreak": "keep-all",
    "wordSpacing": "0px",
    "wordWrap": "break-word",
    "writingMode": "horizontal-tb",
    "x": "0px",
    "y": "0px",
    "zIndex": "auto",
    "zoom": "1"
};

export const Header = ({title,childern}) => {
    return <header>
        <h1 style={titleStyle}>{title}</h1>
        {childern}
    </header>
};
Header.defaultProps = {
    title: 'Caldera Forms',

};


